# -*- coding: utf-8 -*-
"""newproject3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gC63vj4gPxudXglOZAXgW_mhOT87T1Do
"""

def chatbot_response(user_input):
    user_input = user_input.lower().strip()

    if user_input in ["hello", "hi", "hey"]:
        return "Hi there! 👋"
    elif user_input in ["how are you", "how are you doing"]:
        return "I'm fine, thanks! 😊"
    elif user_input in ["bye", "goodbye", "see you"]:
        return "Goodbye! Have a great day! 👋"
    elif user_input in ["what's your name", "who are you"]:
        return "I'm a simple chatbot made with Python. 🤖"
    else:
        return "Sorry, I don't understand that. ❓"

def run_chatbot():
    print("🤖 Chatbot: Hello! Type something to talk. Type 'bye' to exit.\n")

    while True:
        user_input = input("You: ")
        response = chatbot_response(user_input)
        print("Chatbot:", response)

        if user_input.lower().strip() in ["bye", "goodbye", "see you"]:
            break

# Run the chatbot
run_chatbot()