# -*- coding: utf-8 -*-
"""newproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eivLJXqnBHLq1Np0aceuYEWzLFwY8WzP
"""

import random

# Predefined list of 5 words
word_list = ['apple', 'banana', 'grape', 'mango', 'peach']

# Select a random word from the list
word = random.choice(word_list)
guessed_word = ['_'] * len(word)
guessed_letters = []

# Number of allowed incorrect guesses
max_attempts = 6
attempts = 0

print("🎮 Welcome to Hangman!")
print("Guess the word one letter at a time.")
print("You have 6 incorrect attempts.\n")

while attempts < max_attempts and '_' in guessed_word:
    print("Word: ", ' '.join(guessed_word))
    print("Guessed letters:", ' '.join(guessed_letters))
    guess = input("Enter a letter: ").lower()

    if not guess.isalpha() or len(guess) != 1:
        print("❗ Please enter a single letter.\n")
        continue

    if guess in guessed_letters:
        print("⚠️ You already guessed that letter.\n")
        continue

    guessed_letters.append(guess)

    if guess in word:
        print("✅ Good guess!\n")
        for i in range(len(word)):
            if word[i] == guess:
                guessed_word[i] = guess
    else:
        print("❌ Incorrect guess.\n")
        attempts += 1

# Final result
if '_' not in guessed_word:
    print("🎉 Congratulations! You guessed the word:", word)
else:
    print("💀 Game Over! The word was:", word)